stages:
  - compile
  - test

before_script:
  - export CI_HOME="$( pwd )"
  - git submodule update --init --recursive
  - export SCRAM_ARCH="slc6_amd64_gcc530"
  - export CMSSW_VERSION="CMSSW_8_0_19"
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - cd ..
  - scramv1 project CMSSW $CMSSW_VERSION
  - cd $CMSSW_VERSION/src
  - eval `scramv1 runtime -sh`
  - cd $CI_HOME

compile:
  stage: compile
  script:
    - cd $CMSSW_BASE/src
    - mkdir -p TTH
    - cp -r $CI_HOME TTH/
    - cp -R TTH/MEIntegratorStandalone/libs/* $CMSSW_BASE/lib/$SCRAM_ARCH/
    - scram b
    - cd $CMSSW_BASE
    - find src -maxdepth 3 -type d | grep -e "^src/.*/.*/\(interface\|data\|python\)" | tar -czf $CI_HOME/cmssw.tgz lib biglib bin --exclude="*.pyc" --files-from -
  artifacts:
    paths:
      - cmssw.tgz
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 10 minutes

integrator:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - integrator | tee -i integrator.txt
  artifacts:
    paths:
      - integrator.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test0:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - python $CMSSW_BASE/src/TTH/MEIntegratorStandalone/python/run.py $CMSSW_BASE/src/TTH/MEIntegratorStandalone/data/test0.cfg | tee -i test0.txt
  artifacts:
    paths:
      - test0.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"

test1:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - python $CMSSW_BASE/src/TTH/MEIntegratorStandalone/python/run.py $CMSSW_BASE/src/TTH/MEIntegratorStandalone/data/test1.cfg | tee -i test1.txt
  artifacts:
    paths:
      - test1.txt
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
